name: Code Quality Check

on:
  push:
    branches:
      - main
      - feature/**
    paths-ignore:
      - "**/*.md"
      - "**/*.rst"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/*.rst"
  workflow_dispatch:

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      
      - name: Run Biome
        run: biome ci .

      - name: Build with Vite
        run: npm run build
