name: Code Format Check

on:
  push:
    branches:
      - main
      - feature/**
    paths-ignore:
      - "**/*.md"
      - "**/*.rst"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/*.rst"
  workflow_dispatch:

jobs:
  prettier-check:
    name: Prettier Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check formatting with Prettier
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,css,scss,json,md}"
